/**
 * AIFeedback Model
 * Stores high-fidelity structured feedback generated by Groq upon completing an interview.
 */

import mongoose from 'mongoose';

const aiFeedbackSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: [true, 'User ID is required'],
    index: true,
  },
  interviewId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Interview',
    required: [true, 'Interview ID is required'],
  },
  overallScore: {
    type: Number,
    min: 0,
    max: 100,
    required: true,
  },
  overallFeedback: {
    type: String,
    default: '',
  },
  topStrengths: {
    type: [String],
    default: [],
  },
  areasForImprovement: {
    type: [String],
    default: [],
  },
  studyRecommendations: {
    type: [String],
    default: [],
  },
  readinessLevel: {
    type: String,
    enum: ['needs-preparation', 'getting-there', 'interview-ready', 'excellent'],
    default: 'needs-preparation',
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Index for listing user feedback
aiFeedbackSchema.index({ userId: 1, createdAt: -1 });

const AIFeedback = mongoose.model('AIFeedback', aiFeedbackSchema);

export default AIFeedback;
